'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code wird erneut generiert. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class SiteMaster

    ''' <summary>
    ''' A1-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' A2-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' A3-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' A4-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' MainContent-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
